---
# default
default: -p capybara -p chrome-headless

# drivers
capybara: -r features/support/env/capybara.rb
selenium: -r features/support/env/selenium.rb
watir: -r features/support/env/watir.rb

# browser
webkit: BROWSER=webkit
firefox: BROWSER=firefox
chrome: BROWSER=chrome
chrome-headless: BROWSER=chrome:headless
safari: BROWSER=safari
