source "https://rubygems.org"

gem "dumb_delegator"

group :test,
      :development do
  gem "selenium-webdriver"
  gem "watir"
  gem "capybara"
  gem "virtus"

  gem "rake"
  gem "rspec"
  gem "rspec-its"
end
