name: Semantic PR title

on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize

jobs:
  semantic-pr-title:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - uses: dequelabs/semantic-pr-title@8103a3f0c5b4efdc5bdcb70d600e85bcad7cd2f6 # main, ahead of the v1 tag
